# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebaseswift2 (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Pods for firebaseswift2 (iOS)

end

target 'firebaseswift2 (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebaseswift2 (macOS)

end
