# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'

target 'awsTodo (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  # Pods for awsTodo (iOS)

end

target 'awsTodo (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for awsTodo (macOS)

end
